---
title: "Tidyverse Certification Sample Exam"
output:
  md_document:
    variant: gfm
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


### The certification

The Tidyverse Certification is provided by RStudio and it attests to your
pedagogical skills and knowledge of the Tidyverse ecosystem. To obtain the
certification, the first step is to participate in a one-day training course
that focuses on teaching methodologies. Then, you need to pass two exams: a
teaching exam and a Tidyverse exam. For more information on how to get
certified, you can navigate to the
[trainers](https://education.rstudio.com/trainers/) site.


### Sample Test

The Sample Exam is located at
[./sample_exam/exam.html](https://marlycormar.github.io/tidyverse_sample_exam/sample_exam/exam.html).

The Sample Exam with solutions is located at
[./sample_exam_sols/sols.html](https://marlycormar.github.io/tidyverse_sample_exam/sample_exam_sols/sols.html).


### Need help?

Reach out! I am a certified RStudio instructor for both the Tidyverse ecosystem
and Shiny. There are other great trainers out there as well; check out the full
list [here](https://education.rstudio.com/trainers/).

_Notes_:

- The sample exam in this repo comes from the RStudio blog post
[here](https://education.rstudio.com/blog/2020/02/instructor-certification-exams/).
- All the data needed for the exam is located at [./data](./data/).
